version: 2
models:
  - name: stg_dim_companies
    description: Staging company dimension table.
    columns:
      - name: company_id
        description: Primary key for companies data table.
        tests:
          - unique
          - not_null
      - name: name_latest
        description: Company actual name.
        tests:
          - not_null
      - name: name_previous
        description: Company previous names.
  - name: stg_fact_fundamentals
    description: Staging fundamentals data fact table.
    columns:
      - name: company_id
        description: Primary key for companies data.
        tests:
          - not_null
          - relationships:
              to: ref('stg_dim_companies')
              field: company_id
      - name: indicator_id
        description: Indicator name.
        tests:
          - not_null
      - name: year_2010
        description: 2010 values.
      - name: year_2011
        description: 2011 values.
      - name: year_2012
        description: 2012 values.
      - name: year_2013
        description: 2013 values.
      - name: year_2014
        description: 2014 values.
      - name: year_2015
        description: 2015 values.
      - name: year_2016
        description: 2016 values.
